resources:
- ./als
- ./central

# TODO:
# - it may be possible to deploy ALS and Central Ledger in different namespaces, then use their
# default MySQL hosts, and not need to configure that. There's probably no need for them to be in
# the same namespace. Although, perhaps the quoting service calls the ALS? In which case, tying
# them together would be more awkward if they're not in the same namespace.
