apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ml-api-adapter-handler-notification
  name: ml-api-adapter-handler-notification
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/name: ml-api-adapter-handler-notification
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ml-api-adapter-service
  name: ml-api-adapter-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/name: ml-api-adapter-service
