resources:
- ../mojaloop

# Minikube mounts our emptyDir as root into the mysql container. This means mysql cannot access it
# by default. Because we're running in a CI environment with no real data to leak, we'll run the
# mysql container as root.
patches:
- target:
    kind: StatefulSet
    name: .*-mysql
  patch: |
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: ignored
    spec:
      template:
        spec:
          securityContext:
            # runAsUser: 0
            # runAsGroup: 0
            fsGroup: 999


